services:
    redis-server:
        image: 'redis'
        volumes:
          - ./redis:/data 
        command: ["redis-server", "--save", "1 1", "--protected-mode", "no"]
    node-app:
        build: ./
        image: 'docker.io/sudheerkumar10081999/visits'
        ports:
            - "8081:8081"